version: '3.8'

services:
  api:
    build: .
    container_name: key_info_extraction_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./output:/app/output
      - ./models:/app/models
    env_file:
      - .env
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  # 如果需要PostgreSQL数据库，取消下面的注释
  # db:
  #   image: postgres:14
  #   container_name: key_info_extraction_db
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=key_info_extraction
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# 如果使用PostgreSQL，取消下面的注释
# volumes:
#   postgres_data: 